### ISSUE TITLE
Error "you must provide a model parameter"

### ISSUE THREAD

**Issue by teramotodaiki** [nishio/chatgpt-for-kids#1]
https://chatgpt-for-kids-nishio.vercel.app/ にアクセスしてメッセージを入力して「送る」を押すと、 `you must provide a model parameter` というエラーが出ました。

[![Image from Gyazo](https://i.gyazo.com/7def7ee5092332bd062e7669b4cf2f16.png)](https://gyazo.com/7def7ee5092332bd062e7669b4cf2f16)

この辺りで環境変数がささっていないのかも知れません。

https://github.com/nishio/chatgpt-for-kids/blob/1923231c16ee1e787d62e87d5f2daf367f9cfbd6/src/utils/openAI.ts#L5-L22

**Comment by nishio** [comment]
おっと、環境変数で指定した後、サーバの側に設定するのを忘れてました！

ということはその変更以降今までローカルの開発環境でだけGPT4でサーバではGPT3.5だったことになりますね！

**Comment by nishio** [comment]
fixed 19b1056
